repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args:
        - --markdown-linebreak-ext=md
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff # Run the linter.
      - id: ruff-format # Run the formatter.
  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.15.2
      hooks:
      -   id: pyupgrade
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-black
      - id: nbqa-isort
      - id: nbqa-pyupgrade
