from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional, Dict, Any


@dataclass
class ReportArtifact:
    """
    Represents a generated file ready to be saved to disk.
    Contains the raw content and the suggested filename.
    """

    content: str
    filename: str


@dataclass
class MainstreamSourceEntry:
    """
    Represents a chunk of data from a Mainstream 'datapoint' source.
    """

    source_name: str
    content: List[str]  # Flexible: ["Title 1", "Title 2"] OR ["Full scraped text..."]
    source_type: str  # 'youtube' or 'webpage'


@dataclass
class MainstreamHeadlines:
    """
    Container for all mainstream source entries.
    """

    entries: List[MainstreamSourceEntry]


@dataclass
class SourceHeadlines:
    """
    Helper class: Contains all titles from a single source, maintaining rank order.
    Example: Tricontinental -> ["Title 1", "Title 2"]
    """

    source_name: str
    titles: List[str]


@dataclass
class AnalysisHeadlines:
    """
    Consolidated view of analysis articles.
    Now represents a flat list of sources without a top-level region grouping.
    """

    source_groups: List[SourceHeadlines]


@dataclass
class MaterialistAnalysisEntry:
    """
    Holds the generated analysis for a specific region.
    """

    region: str
    analysis: str


@dataclass
class MaterialistAnalyses:
    """
    Container for all regional analyses generated in Phase 4.
    """

    entries: List[MaterialistAnalysisEntry]


@dataclass
class GeopoliticalLedger:
    """
    Holds the output of the Geopolitical Ledger Generator.
    Since the LLM is instructed to produce a strict Markdown table,
    we store the content as a raw string to preserve formatting.
    """

    date: datetime
    ledger_content: str  # The full markdown table + title generated by the LLM


@dataclass
class Article:
    """
    The core unit of information in the pipeline.
    Acts as both the input (Raw) and the output (Enriched/Brief).
    """

    # Core Metadata
    title: str
    source: str
    url: str
    date_collected: datetime = field(default_factory=datetime.now)

    # Payload
    raw_content: str = ""
    summary: Optional[str] = None  # Generated summary text

    # Extra data (rank, tags, original HTML)
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_summarized(self) -> bool:
        """Helper to check if this article has been processed."""
        return self.summary is not None


@dataclass
class RegionalBriefingEntry:
    """
    A single synthesized region.
    Separates the public narrative from the strategic reality.
    """

    region: str
    mainstream_narrative: str  # What the news is reporting
    strategic_analysis: str  # The materialist/strategic reality


@dataclass
class GlobalBriefing:
    """
    The final output of Phase 5.
    """

    entries: List[RegionalBriefingEntry]
    date: datetime = field(default_factory=datetime.now)
