from dataclasses import dataclass
from typing import List
from datetime import datetime


@dataclass
class ReportArtifact:
    """
    Represents a generated file ready to be saved to disk.
    Contains the raw content and the suggested filename.
    """

    content: str
    filename: str


@dataclass
class MainstreamSourceEntry:
    """
    Represents a chunk of data from a Mainstream 'datapoint' source.
    """

    source_name: str
    content: List[str]  # Flexible: ["Title 1", "Title 2"] OR ["Full scraped text..."]
    source_type: str  # 'youtube' or 'webpage'


@dataclass
class MainstreamHeadlines:
    """
    Container for all mainstream source entries.
    """

    entries: List[MainstreamSourceEntry]


@dataclass
class SourceHeadlines:
    """
    Helper class: Contains all titles from a single source, maintaining rank order.
    Example: Tricontinental -> ["Title 1", "Title 2"]
    """

    source_name: str
    titles: List[str]


@dataclass
class AnalysisHeadlines:
    """
    Consolidated view of analysis articles.
    Now represents a flat list of sources without a top-level region grouping.
    """

    source_groups: List[SourceHeadlines]


@dataclass
class MaterialistAnalysisEntry:
    """
    Holds the generated analysis for a specific region.
    """

    region: str
    analysis: str


@dataclass
class MaterialistAnalyses:
    """
    Container for all regional analyses generated in Phase 4.
    """

    entries: List[MaterialistAnalysisEntry]


@dataclass
class GeopoliticalLedger:
    """
    Holds the output of the Geopolitical Ledger Generator.
    Since the LLM is instructed to produce a strict Markdown table,
    we store the content as a raw string to preserve formatting.
    """

    date: datetime
    ledger_content: str  # The full markdown table + title generated by the LLM
